[package]
name = "quant-challenge"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3.19"
async-trait = "0.1"
anyhow = "1"

[features]
default = []
